#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
#ynh_script_progression "Setting up source files..."

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
#ynh_script_progression "Adding $app's configuration files..."

#=================================================
# SYSTEM CONFIGURATION
#=================================================
#ynh_script_progression "Adding system configurations related to $app..."

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"