#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
#ynh_script_progression "Removing system configurations related to $app..."

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"