#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
#ynh_script_progression "Ensuring downward compatibility..."

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
#ynh_script_progression "Upgrading system configurations related to $app..."

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"